#!/bin/sh

# Получаем список C/C++ файлов в коммите
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(cpp|c|cc|cxx|h|hpp)$')

if [ -z "$files" ]; then
    exit 0
fi

echo "Running clang-format..."
for file in $files; do
    clang-format -i "$file"
    git add "$file"
done

echo "Running clang-tidy..."
for file in $files; do
    clang-tidy "$file" -p build --quiet
    if [ $? -ne 0 ]; then
        echo "clang-tidy failed on $file"
        exit 1
    fi
done


exit 0
